services:
  pg:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_DB: ${APP_CONFIG__DB__NAME}
      POSTGRES_USER: ${APP_CONFIG__DB__USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASSWORD}
    ports:
      - "46003:5432"
  pg_test:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_DB: shop_test
      POSTGRES_USER: user_test
      POSTGRES_PASSWORD: password_test
    ports:
      - "46004:5432"

