services:
  backend:
    container_name: backend
    build:
      context: ./backend
    expose:
      - 8000
    env_file:
      - backend/.env
    depends_on:
      - pg

  pg:
    container_name: database
    image: postgres:17.4-alpine
    env_file:
      - backend/.env
    environment:
      POSTGRES_DB: APP_CONFIG__DB__NAME
      POSTGRES_USER: APP_CONFIG__DB__USER
      POSTGRES_PASSWORD: APP_CONFIG__DB__PASSWORD