services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - pg

  pg:
    container_name: database
    image: postgres:17.4-alpine
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password