services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8001:8000"
#    command: sh -c 'echo 123; echo 456; poetry run python main.py'
    depends_on:
      - pg

  pg:
    container_name: database
    image: postgres:17.4-alpine
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "46003:5432"