services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "46003:5432"
  pg_test:
    image: postgres
    environment:
      POSTGRES_DB: shop_test
      POSTGRES_USER: user_test
      POSTGRES_PASSWORD: password_test
    ports:
      - "46004:5432"
