"""posts fk for users

Revision ID: faa06b4a2319
Revises: 700ec5f88976
Create Date: 2025-02-17 10:33:24.953113

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "faa06b4a2319"
down_revision: Union[str, None] = "700ec5f88976"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "microblog_posts", sa.Column("user", sa.Integer(), nullable=True)
    )
    op.drop_index("ix_microblog_posts_id", table_name="microblog_posts")
    op.create_foreign_key(
        op.f("fk_microblog_posts_user_users"),
        "microblog_posts",
        "users",
        ["user"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_microblog_posts_user_users"),
        "microblog_posts",
        type_="foreignkey",
    )
    op.create_index(
        "ix_microblog_posts_id", "microblog_posts", ["id"], unique=True
    )
    op.drop_column("microblog_posts", "user")
    # ### end Alembic commands ###
