"""post parent relation

Revision ID: 5dac09c78915
Revises: 67348a007390
Create Date: 2025-02-17 13:11:47.209831

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5dac09c78915"
down_revision: Union[str, None] = "67348a007390"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "microblog_posts", sa.Column("parent_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_microblog_posts_parent_id_microblog_posts"),
        "microblog_posts",
        "microblog_posts",
        ["parent_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_microblog_posts_parent_id_microblog_posts"),
        "microblog_posts",
        type_="foreignkey",
    )
    op.drop_column("microblog_posts", "parent_id")
    # ### end Alembic commands ###
