"""fix post table(no parent)

Revision ID: 974a61385f34
Revises: 5dac09c78915
Create Date: 2025-02-24 22:30:39.418509

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "974a61385f34"
down_revision: Union[str, None] = "5dac09c78915"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_access_tokens_created_at", table_name="access_tokens")
    op.drop_table("access_tokens")
    op.add_column(
        "microblog_posts", sa.Column("user_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "fk_microblog_posts_user_users", "microblog_posts", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_microblog_posts_parent_id_microblog_posts",
        "microblog_posts",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_microblog_posts_user_id_users"),
        "microblog_posts",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_column("microblog_posts", "user")
    op.drop_column("microblog_posts", "parent_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "microblog_posts",
        sa.Column(
            "parent_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "microblog_posts",
        sa.Column("user", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        op.f("fk_microblog_posts_user_id_users"),
        "microblog_posts",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_microblog_posts_parent_id_microblog_posts",
        "microblog_posts",
        "microblog_posts",
        ["parent_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_microblog_posts_user_users",
        "microblog_posts",
        "users",
        ["user"],
        ["id"],
    )
    op.drop_column("microblog_posts", "user_id")
    op.create_table(
        "access_tokens",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "token", sa.VARCHAR(length=43), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_access_tokens_user_id_users",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        "ix_access_tokens_created_at",
        "access_tokens",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
