"""fix post table(null in user id 2)

Revision ID: 713cacfa1670
Revises: 45e5a8213b91
Create Date: 2025-02-25 19:35:15.655880

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "713cacfa1670"
down_revision: Union[str, None] = "45e5a8213b91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "posts", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "posts", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
